export enum APP_FRAMEWORK {
    UNIVERSAL = 0,
    VDOM = 1,
    ANDROID = 1 << 1,
    CHROME = 1 << 2
}

export enum APP_SECTION {
    DOM_TRAVERSE = 1,
    EXTENSION = 1 << 1,
    RENDER = 1 << 2,
    ALL = DOM_TRAVERSE | EXTENSION | RENDER
}

export enum NODE_RESOURCE {
    BOX_STYLE = 1,
    BOX_SPACING = 1 << 1,
    FONT_STYLE = 1 << 2,
    VALUE_STRING = 1 << 3,
    IMAGE_SOURCE = 1 << 4,
    ASSET = FONT_STYLE | VALUE_STRING | IMAGE_SOURCE,
    ALL = BOX_STYLE | BOX_SPACING | ASSET
}

export enum NODE_PROCEDURE {
    CONSTRAINT = 1,
    LAYOUT = 1 << 1,
    ALIGNMENT = 1 << 2,
    ACCESSIBILITY = 1 << 3,
    LOCALIZATION = 1 << 4,
    CUSTOMIZATION = 1 << 5,
    ALL = CONSTRAINT | LAYOUT | ALIGNMENT | ACCESSIBILITY | LOCALIZATION | CUSTOMIZATION
}