import { UserSettingsAndroid } from '../../@types/android/application';

const settings: UserSettingsAndroid = {
    builtInExtensions: [
        'android.delegate.max-width-height',
        'android.delegate.fixed',
        'android.delegate.negative-x',
        'android.delegate.negative-viewport',
        'android.delegate.percent',
        'android.delegate.scrollbar',
        'android.delegate.background',
        'android.delegate.css-grid',
        'android.delegate.radiogroup',
        'squared.sprite',
        'squared.css-grid',
        'squared.flexbox',
        'squared.table',
        'squared.list',
        'squared.grid',
        'squared.relative',
        'squared.verticalalign',
        'squared.whitespace',
        'squared.accessibility',
        'android.resource.svg',
        'android.resource.background',
        'android.resource.strings',
        'android.resource.fonts',
        'android.resource.dimens',
        'android.resource.styles',
        'android.resource.includes'
    ],
    targetAPI: 29,
    resolutionDPI: 160,
    resolutionScreenWidth: 1280,
    resolutionScreenHeight: 900,
    framesPerSecond: 60,
    supportRTL: true,
    preloadImages: true,
    supportNegativeLeftTop: true,
    exclusionsDisabled: false,
    customizationsOverwritePrivilege: true,
    showAttributes: true,
    createQuerySelectorMap: false,
    convertPixels: 'dp',
    insertSpaces: 4,
    handleExtensionsAsync: true,
    autoCloseOnWrite: true,
    showErrorMessages: true,
    manifestLabelAppName: 'android',
    manifestThemeName: 'AppTheme',
    manifestParentThemeName: 'Theme.AppCompat.Light.NoActionBar',
    outputMainFileName: 'activity_main.xml',
    outputDirectory: 'app/src/main',
    outputArchiveName: 'android-xml',
    outputArchiveFormat: 'zip',
    outputArchiveTimeout: 30
};

export default settings;